# Generated by Django 6.0.4 on 2026-07-29 11:18

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PosTicketHeader',
            fields=[
                ('ticket_id', models.CharField(max_length=60, primary_key=True, serialize=False)),
                ('id_tercero', models.CharField(default='222222222222', max_length=20)),
                ('nom_tercero', models.CharField(default='VENTAS MASIVAS (CONSUMIDOR FINAL)', max_length=200)),
                ('fch_ticket', models.DateTimeField()),
                ('tot_mercancia', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15)),
                ('tot_iva', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15)),
                ('tot_ticket', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15)),
                ('pago_efectivo', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15)),
                ('pago_tarjeta', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15)),
                ('pago_transferencia', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15)),
                ('cambio', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15)),
                ('sync_status', models.BooleanField(default=True)),
                ('consolidado_cierre', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PosTurno',
            fields=[
                ('id_turno', models.BigAutoField(primary_key=True, serialize=False)),
                ('caja_id', models.CharField(default='CAJA-01', max_length=20)),
                ('usuario', models.CharField(default='cajero', max_length=50)),
                ('base_economica', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15)),
                ('fch_apertura', models.DateTimeField(auto_now_add=True)),
                ('fch_cierre', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(default='ABIERTO', max_length=15)),
                ('tot_ventas_efectivo', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15)),
                ('tot_ventas_tarjeta', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15)),
                ('tot_ventas_transferencia', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15)),
                ('id_documento_cierre', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PosTicketDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_articulo', models.CharField(max_length=15)),
                ('referencia', models.CharField(blank=True, default='', max_length=30)),
                ('nom_articulo', models.CharField(max_length=150)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=12)),
                ('vlr_unitario', models.DecimalField(decimal_places=2, max_digits=15)),
                ('porc_descuento', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5)),
                ('porc_iva', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5)),
                ('vlr_iva', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15)),
                ('tot_linea', models.DecimalField(decimal_places=2, max_digits=15)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pos.posticketheader')),
            ],
        ),
        migrations.AddField(
            model_name='posticketheader',
            name='turno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='pos.posturno'),
        ),
    ]
