# Generated by Django 6.0.4 on 2026-07-29 14:15

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PosPuntosCliente',
            fields=[
                ('id_tercero', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('puntos_saldo', models.IntegerField(default=0)),
                ('puntos_acumulados', models.IntegerField(default=0)),
                ('puntos_redimidos', models.IntegerField(default=0)),
                ('fch_actualizacion', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PrPromocion',
            fields=[
                ('id_promocion', models.BigAutoField(primary_key=True, serialize=False)),
                ('nom_promocion', models.CharField(max_length=150)),
                ('fch_inicio', models.DateTimeField()),
                ('fch_fin', models.DateTimeField()),
                ('activo', models.BooleanField(default=True)),
                ('prioridad', models.IntegerField(default=1)),
            ],
        ),
        migrations.AddField(
            model_name='posticketheader',
            name='descuento_promocion',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15),
        ),
        migrations.AddField(
            model_name='posticketheader',
            name='pago_puntos',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15),
        ),
        migrations.AddField(
            model_name='posticketheader',
            name='puntos_ganados',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='posticketheader',
            name='puntos_redimidos_ticket',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='PrCondicion',
            fields=[
                ('id_condicion', models.BigAutoField(primary_key=True, serialize=False)),
                ('tipo_condicion', models.CharField(choices=[('MONTO_MINIMO', 'Monto Mínimo de Compra'), ('PRODUCTO', 'Producto Específico'), ('CLIENTE', 'Cliente Específico')], max_length=30)),
                ('valor_condicion', models.CharField(max_length=100)),
                ('cantidad_minima', models.DecimalField(decimal_places=2, default=Decimal('1'), max_digits=12)),
                ('promocion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='condiciones', to='pos.prpromocion')),
            ],
        ),
        migrations.CreateModel(
            name='PrAccion',
            fields=[
                ('id_accion', models.BigAutoField(primary_key=True, serialize=False)),
                ('tipo_accion', models.CharField(choices=[('DESCUENTO_PORC', 'Porcentaje de Descuento (%)'), ('DESCUENTO_VALOR', 'Valor Fijo de Descuento ($ COP)'), ('REGALO', 'Artículo de Regalo ($0 COP)')], max_length=30)),
                ('valor_accion', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15)),
                ('id_articulo_regalo', models.CharField(blank=True, max_length=20, null=True)),
                ('promocion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acciones', to='pos.prpromocion')),
            ],
        ),
    ]
